### ISSUE TITLE
出现not found config of "dice"类似的问题

### ISSUE THREAD

**Issue by githubdl** [sanshanya/hoshino_xcw#3]
![image](https://user-images.githubusercontent.com/29683723/98440883-5ac8ed00-2136-11eb-94b1-cfad5d12751b.png)
请问这个问题如何解决呢？（我是按照你的一键配置来设置的，给机器人发“在？”也是有回复的）

**Comment by sanshanya** [comment]
1.你使用过一键装依赖吗?
2."warning"在通常情况下不会影响正常运行,你也可以考虑在'config'文件夹创建同名的'XXX.py'来避免warning
