### ISSUE TITLE
win版本的对吗

### ISSUE THREAD

**Issue by dnslin** [sanshanya/hoshino_xcw#6]
请问有linux版吗

**Comment by sanshanya** [comment]
可以参考https://blog.di.he.cn/2020/09/22/deploy-a-priconne-bot-on-linux/




---原始邮件---
发件人: "Gin_Nide"<notifications@github.com&gt;
发送时间: 2020年12月16日(周三) 下午2:28
收件人: "sanshanya/hoshino_xcw"<hoshino_xcw@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [sanshanya/hoshino_xcw] win版本的对吗 (#6)




 
请问有linux版吗
